name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: List Xcode versions
      run: ls -n /Applications/ | grep Xcode
      
    - name: List
      run: ls
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12_beta.app
      
    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
